"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, CreditCard, LockKeyhole } from "lucide-react";
import { doc, getDoc, getDocs, limit, query, setDoc, where, collection } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";
import { genres, site } from "@/lib/site";
import { getFirebaseAuth, getFirebaseBrowserConfigError, getFirebaseDb } from "@/lib/firebase/client";
type FormState = { bookId: string; name: string; email: string; genre: string; summary: string; };
const createBookId = () => globalThis.crypto.randomUUID();
export function NewStoryForm() { const auth = getFirebaseAuth(); const db = getFirebaseDb(); const [form, setForm] = useState<FormState>({ bookId: typeof window === "undefined" ? "" : createBookId(), name: "", email: "", genre: genres[0], summary: "" }); const [message, setMessage] = useState(getFirebaseBrowserConfigError() ? "Order access is temporarily unavailable. Please try again later." : "Tell us about the novel you want to create."); const [isSubmitting, setIsSubmitting] = useState(false); const validation = useMemo(() => { if (!auth || !db) return "Order access is temporarily unavailable. Please try again later."; if (form.name.trim().length < 2) return "Enter your name."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) return "Enter a valid email address."; if (form.summary.trim().length < 40) return "Add at least 40 characters to the story summary."; return null; }, [auth, db, form]);
useEffect(() => { if (!auth || !db) return; const unsubscribe = onAuthStateChanged(auth, async (user) => { if (!user) { window.location.href = "/login"; return; } const profile = await getDoc(doc(db, "profiles", user.uid)); const latest = await getDocs(query(collection(db, "story_orders"), where("user_id", "==", user.uid), limit(1))); const order = latest.docs[0]?.data(); const profileData = profile.data(); setForm((current) => ({ ...current, email: current.email || profileData?.email || order?.email || user.email || "", name: current.name || profileData?.full_name || order?.name || user.displayName || (user.email?.split("@")[0] ?? "") })); }); return unsubscribe; }, [auth, db]);
const set = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!auth || !db || !auth.currentUser) return; setIsSubmitting(true); setMessage("Saving your order..."); const user = auth.currentUser; const createdAt = new Date().toISOString(); try { await setDoc(doc(db, "story_orders", form.bookId), { id: form.bookId, user_id: user.uid, name: form.name.trim(), email: form.email.trim(), genre: form.genre, summary: form.summary.trim(), stripe_checkout_session_id: null, stripe_payment_status: "unpaid", story_status: "pending_payment", n8n_response: null, created_at: createdAt, updated_at: createdAt }); await setDoc(doc(db, "profiles", user.uid), { id: user.uid, email: form.email.trim(), full_name: form.name.trim(), updated_at: createdAt }, { merge: true }); window.location.href = `/dashboard?checkout=${encodeURIComponent(form.bookId)}`; } catch { setIsSubmitting(false); setMessage("We could not save your order. Please try again."); } }
const disabled = isSubmitting; return <form onSubmit={submit} className="rounded-lg border border-[#dbe5df] bg-white p-6 shadow-sm sm:p-8"><div><label htmlFor="book-id" className="text-sm font-semibold text-[#101513]">Book ID</label><input id="book-id" className="field mt-2 font-mono text-sm text-[#52615a]" value={form.bookId} readOnly suppressHydrationWarning /><p className="mt-2 text-xs leading-5 text-[#6f7d76]">Keep this ID in case you do not receive your novel manuscript within one day of ordering.</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-[#101513]">Name<input className="field mt-2" value={form.name} onChange={(e) => set("name", e.target.value)} required minLength={2} disabled={disabled} /></label><label className="text-sm font-semibold text-[#101513]">Email<input type="email" className="field mt-2" value={form.email} onChange={(e) => set("email", e.target.value)} required disabled={disabled} /></label></div><label className="mt-5 block text-sm font-semibold text-[#101513]">Novel genre<select className="field mt-2" value={form.genre} onChange={(e) => set("genre", e.target.value)} disabled={disabled}>{genres.map((genre) => <option key={genre}>{genre}</option>)}</select></label><label className="mt-5 block text-sm font-semibold text-[#101513]">Story summary<textarea className="field mt-2 min-h-48 resize-y" value={form.summary} onChange={(e) => set("summary", e.target.value)} minLength={40} maxLength={5000} required disabled={disabled} /></label><p className="mt-2 text-xs text-[#6f7d76]">{form.summary.length}/5000 characters</p><div className="mt-7 flex flex-col gap-4 border-t border-[#dbe5df] pt-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3 text-sm leading-6 text-[#52615a]"><LockKeyhole aria-hidden="true" size={18} className="mt-1 shrink-0 text-[#007a4d]" /><span>Your story details and Book ID stay with your order. Work on your novel manuscript begins after payment is confirmed.</span></div><button type="submit" disabled={!!validation || disabled} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-full bg-[#007a4d] px-6 py-3.5 font-semibold text-white disabled:opacity-55"><CreditCard aria-hidden="true" size={18} />Continue to {site.price}<ArrowRight aria-hidden="true" size={18} /></button></div><p role="status" aria-live="polite" className="mt-5 text-sm leading-6 text-[#52615a]">{validation ?? message}</p></form>; }